package day1223;

public class Ex7Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr = {4,5,6,7};
		for(int i=0; i<=arr.length;i++) {
			try {
				System.out.println(arr[i]);
			} catch (Exception e) {
				// TODO: handle exception
				System.out.println("오류 메세지: "+e.getMessage());
				e.printStackTrace(); // 행 번호 표시
			}
		}
		System.out.println("정상 종료");

	}

}
